version: '3.8'

services:
  app:
    build: .
    ports:
      - "8529:8529"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_coder
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_NAME=ai_coder
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_coder
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
