version: '3.8'

services:
  ai_coder:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai_coder:latest
    container_name: ai_coder
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      internal_db:
        condition: service_healthy
      internal_redis:
        condition: service_healthy
    networks:
      - ai_coder_network

  internal_db:
    image: postgres:15-alpine
    container_name: ai_coder_internal_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai_coder
      POSTGRES_PASSWORD: local_db_password
      POSTGRES_DB: ai_coder_db
    volumes:
      - internal_postgres_data:/var/lib/postgresql/data
    networks:
      - ai_coder_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_coder"]
      interval: 10s
      timeout: 5s
      retries: 5

  internal_redis:
    image: redis:7-alpine
    container_name: ai_coder_internal_redis
    restart: unless-stopped
    command: redis-server --requirepass local_redis_password
    volumes:
      - internal_redis_data:/data
    networks:
      - ai_coder_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "local_redis_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ai_coder_network:
    driver: bridge

volumes:
  internal_postgres_data:
  internal_redis_data:
